name: Fork

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"

jobs:
  Fork:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v4.1.7

    - name: Edit Loon/Plugin
      run: |
        cd Loon/Plugin
        for file in *.plugin; do
          if [ "$file" ] ; then
            
            # 保留特定的行和其他行，删除空行，并在第三行插入 #!icon
            awk '
              /^#!name =|^#!desc =/ { print }
              NR == 3 { print "#!icon = https://github.com/Auniquesir/Box/raw/X/icon/App/unun.png" }
              /^[[]/ { print ""; print; next }
              /^[^#]/ { if(NF) print }
            ' "$file" > tmpfile
            mv tmpfile "$file"

            # 检查并删除临时文件
            if [ -f tmpfile ]; then
              rm tmpfile
            fi
          else
            echo "$file not found."
          fi
        done


      # Fork 插件、脚本
    - name: Fork Plugin&Script
      run: |
        # rm -rf Loon/Plugin/*
        # rm -rf Loon/Script/*
        mkdir -p Loon/Plugin/
        mkdir -p Loon/Script/
        git clone https://gitlab.com/lodepuly/vpn_tool.git temp_directory
        cp -r temp_directory/Tool/Loon/Plugin/* Loon/Plugin/
        cp -r temp_directory/Resource/Script/* Loon/Script/
        rm -rf temp_directory   

      # 修改脚本链接
    - name: Edit Loon/Plugin
      run: |
        cd Loon/Plugin
        for file in *.plugin; do
          if [ "$file" ] ; then
            # 修改脚本链接
            sed -i 's%gitlab\.com/lodepuly/vpn_tool/-/raw/master/Resource/Script%raw.githubusercontent.com/Auniquesir/Tool/X/Loon/Script%g' "$file"
            
            # 保留特定的行和其他行，保留空行
            # awk '/^#!name =|^#!desc =|^#!icon =|^$|^[^#]/' "$file" > tmpfile
            # 保留特定的行和其他行，删除空行
            awk '/^#!name =|^#!desc =|^#!icon =/ { print } /^[[]/ { print ""; print; next } /^[^#]/ { if(NF) print }' "$file" > tmpfile
            mv tmpfile "$file"

            # 检查并删除临时文件
            if [ -f tmpfile ]; then
              rm tmpfile
            fi
          else
            echo "$file not found."
          fi
        done
        

    - name: Add and Commit
      run: |
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git pull --rebase origin X
          git push origin X
        else
          echo "No changes to commit."
        fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
