
name: Fork icon

on:
  workflow_dispatch:

jobs:
  Forkicon:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v4.1.7

    # 拉取文件
    - name: Clone Rules
      run: |
        # 定义目标目录和仓库克隆链接
        rules_dir="icon"
        repo_url="https://github.com/blackmatrix7/ios_rule_script.git"

        # 创建目标目录并克隆仓库
        mkdir -p "$rules_dir"
        git clone "$repo_url" temp_directory || true

        # 复制文件
        if [ -d "temp_directory/icon" ]; then
          cp -r temp_directory/icon/* "$rules_dir/"
        fi

        # 清理临时目录
        rm -rf temp_directory

    # 添加并提交更改
    - name: Add and Commit
      run: |
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git pull --rebase origin X
          git push origin X
        else
          echo "No changes to commit."
        fi

    # 清理工作流
    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
